// Writes packages/kernel/src/version.ts from the root package.json.
//
// Generated rather than imported: an ESM `import ... with { type: 'json' }` of a file
// that sits outside the compiled tree resolves differently from src and from dist,
// and this costs four lines instead. The file is gitignored.
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const { version } = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'))

await writeFile(
  join(root, 'packages/kernel/src/version.ts'),
  `// GENERATED by scripts/gen-version.mjs — do not edit, do not commit.\nexport const VERSION = '${version}'\n`,
  'utf8',
)
